/* ============================================================
   storage.js — progress mirror + server sync (ES5)
   ------------------------------------------------------------
   Phase 1 (server-authoritative): the server owns the truth.
   This module keeps an in-memory mirror `S` so the UI stays
   instant, writes durable changes through to the API, and
   reconciles the mirror from the authoritative snapshot the
   server returns. A localStorage copy is kept ONLY as an
   offline cache so a flaky school network never bricks a lesson.

   The rest of the app still calls Storage.save(S) / reads S
   exactly as before — the network details live here.

   M9 adds the OFFLINE QUEUE (brief §8). A student on a school phone loses
   the network mid-lesson; today the POST fails and the progress is gone.
   From now on api.js hands the failed (or never-attempted, when we know we
   are offline) POST to enqueue() below, and flush() replays it FIFO when the
   connection returns. Every action carries a client-generated EVENT ID so a
   replay after bad wifi is idempotent on the server side rather than paying
   XP twice. See the "offline queue" block for the full contract.
   ============================================================ */
var Storage = (function () {
  'use strict';

  var KEY = 'mariane_cache_v2';       /* offline cache (not the source of truth) */
  var LEGACY_KEY = 'mariane_save_v1'; /* old local-only save, for one-time import */
  var QKEY = 'mariane_queue_v1';      /* the offline action queue (brief §8) */
  var syncTimer = null;

  function defaultState() {
    return {
      name: '',
      xp: 0,
      hearts: 5,
      maxHearts: 5,
      streak: 0,
      lastDay: '',
      completed: {},
      bosses: {},
      mapNode: 'f1',
      createdAt: new Date().getTime()
    };
  }

  /* ---- offline cache (best-effort, never authoritative) ---- */
  function writeCache(state) {
    try { window.localStorage.setItem(KEY, JSON.stringify(state)); } catch (e) { /* noop */ }
  }
  function readCache() {
    try {
      var raw = window.localStorage.getItem(KEY);
      return raw ? JSON.parse(raw) : null;
    } catch (e) { return null; }
  }

  /* ============================================================
     OFFLINE QUEUE (brief §8)
     ------------------------------------------------------------
     CONTRACT (client side ships now; the server may ignore the id today):

       * Every queueable POST carries an EVENT ID generated by the client
         (see eventId()). api.js sends it as the `X-Event-Id` header AND as
         an `eventId` field in the JSON body — the same value, twice, because
         some shared hosts strip unknown request headers. A server that wants
         dedup stores the id per student and answers a repeat with the same
         snapshot instead of granting the reward twice.
       * The id is created ONCE, at the moment the action happens, and is
         reused for every replay of that action. That is the whole point: a
         POST that reached the server but whose RESPONSE was lost to bad wifi
         gets replayed with the id the server already saw.
       * Queue order is FIFO and flush() stops at the FIRST failure, so a
         step never overtakes the step before it.
       * flush() never busy-loops: it is guarded by a `flushing` flag and
         re-armed by a capped exponential backoff timer (RETRY_MIN..RETRY_MAX)
         or by the browser's `online` event, whichever comes first.
       * The queue is CAPPED. When it is full the eviction is by PRIORITY,
         oldest-first inside a priority: a `sync` (hearts/map position, pure
         convenience) is dropped long before a `step_complete` (earned
         progress). A step_complete is never dropped to make room for a sync;
         if the newcomer is the least valuable thing in a full queue, the
         NEWCOMER is what gets refused.
     ============================================================ */

  var QMAX = 200;                 /* entries; ~40 KB of JSON worst case */
  var RETRY_MIN = 4000;           /* first backoff after a failed flush */
  var RETRY_MAX = 300000;         /* 5 minutes — never hammer a dead server */
  var flushing = false;           /* re-entrancy guard (this is the busy-loop lock) */
  var retryTimer = null;
  var retryDelay = 0;
  var forcedOffline = false;      /* test/debug flag; see setOffline() */
  var idSeq = 0;

  /* How precious is each action? Bigger survives longer under pressure.
     Anything unknown sits in the middle: a future endpoint is assumed to
     matter more than a sync and less than earned progress. */
  var PRIORITY = {
    'step_complete.php': 3,
    'boss_quiz.php': 3,
    'boss_fight.php': 3,
    'boss_result.php': 1,        /* a record-board measurement, not progress */
    'sync.php': 0                /* hearts + map node: last write wins anyway */
  };
  function priorityOf(path) {
    return PRIORITY.hasOwnProperty(path) ? PRIORITY[path] : 2;
  }

  /* uuid-ish, no dependency: time + a per-session counter + randomness.
     The counter is what makes two events in the SAME millisecond distinct;
     Math.random alone collides more often than people expect. */
  function eventId() {
    idSeq = (idSeq + 1) % 100000;
    return 'e' + (new Date().getTime()).toString(36) +
           '-' + idSeq.toString(36) +
           '-' + Math.floor(Math.random() * 1679616).toString(36);
  }

  function readQueue() {
    try {
      var raw = window.localStorage.getItem(QKEY);
      var q = raw ? JSON.parse(raw) : [];
      return Object.prototype.toString.call(q) === '[object Array]' ? q : [];
    } catch (e) { return []; }
  }
  function writeQueue(q) {
    try { window.localStorage.setItem(QKEY, JSON.stringify(q)); return true; }
    catch (e) { return false; }   /* quota/private mode: the action is lost, loudly below */
  }

  /* Are we allowed to talk to the server right now? navigator.onLine is a
     weak signal (it only knows about the network interface, not the wifi
     portal upstairs), so it is used as a "definitely offline" hint only —
     a false negative just means we try, fail, and queue. */
  function isOffline() {
    if (forcedOffline) { return true; }
    return (typeof navigator !== 'undefined' && navigator.onLine === false);
  }
  /* Test/debug hook: force the offline branch without unplugging anything. */
  function setOffline(flag) {
    forcedOffline = !!flag;
    if (!forcedOffline) { retryDelay = 0; flush(); }
    return forcedOffline;
  }

  /* Queue one action. `id` is optional: pass the id api.js already generated
     for the live attempt so the replay is the SAME event, not a new one.
     Returns the stored item, or null when the action was refused/undroppable. */
  function enqueue(path, body, id) {
    var q = readQueue();
    var item = {
      id: id || eventId(),
      path: path,
      body: body || {},
      prio: priorityOf(path),
      ts: new Date().getTime(),
      tries: 0
    };

    /* COLLAPSE syncs. sync.php is "set hearts + map node to these values";
       ten queued syncs are nine wasted requests and the last one wins anyway.
       Progress endpoints are never collapsed — each one is a distinct event. */
    if (path === 'sync.php') {
      var kept = [], i;
      for (i = 0; i < q.length; i++) {
        if (q[i].path !== 'sync.php') { kept.push(q[i]); }
      }
      q = kept;
    }

    /* CAP. Evict the oldest entry of the lowest priority present; refuse the
       newcomer instead if IT is the least valuable thing here. */
    while (q.length >= QMAX) {
      var victim = -1, lowest = item.prio;
      for (var j = 0; j < q.length; j++) {
        if (q[j].prio < lowest) { lowest = q[j].prio; victim = j; }
      }
      if (victim < 0) {
        /* everything queued is at least as precious as the newcomer */
        if (window.console) {
          console.warn('[storage] queue full (' + q.length + '); refused ' + path);
        }
        return null;
      }
      q.splice(victim, 1);
      if (window.console) {
        console.warn('[storage] queue full; dropped a queued ' + item.path +
                     ' of lower priority to keep earned progress');
      }
    }

    q.push(item);
    if (!writeQueue(q) && window.console) {
      console.warn('[storage] could not persist the offline queue (storage full?)');
    }
    return item;
  }

  function queueLength() { return readQueue().length; }
  /* a COPY, for tests and for a future "n actiōnēs pendent" indicator */
  function queuePeek() { return readQueue(); }
  function clearQueue() {
    try { window.localStorage.removeItem(QKEY); } catch (e) { /* noop */ }
    if (retryTimer) { window.clearTimeout(retryTimer); retryTimer = null; }
    retryDelay = 0;
  }

  function removeById(id) {
    var q = readQueue(), out = [], i;
    for (i = 0; i < q.length; i++) { if (q[i].id !== id) { out.push(q[i]); } }
    writeQueue(out);
  }

  function scheduleRetry() {
    retryDelay = retryDelay ? Math.min(retryDelay * 2, RETRY_MAX) : RETRY_MIN;
    if (retryTimer) { window.clearTimeout(retryTimer); }
    retryTimer = window.setTimeout(function () {
      retryTimer = null;
      flush();
    }, retryDelay);
  }

  /* Replay the queue head-first. Stops at the first failure and comes back
     later; it never spins. cb(sentCount) is optional (tests use it). */
  function flush(cb) {
    cb = cb || function () {};
    if (flushing) { cb(0); return; }
    if (typeof Api === 'undefined' || !Api.replay) { cb(0); return; }
    if (isOffline()) { cb(0); return; }
    /* Every queueable endpoint requires the CSRF token, which only exists
       after me.php/login.php has answered. Flushing before then would burn
       the whole queue on 403s, so we simply wait — Api.setCsrf() calls us
       back the moment the token arrives. */
    if (Api.getCsrf && !Api.getCsrf()) { cb(0); return; }
    if (readQueue().length === 0) { retryDelay = 0; cb(0); return; }

    flushing = true;
    var sent = 0;

    function step() {
      var q = readQueue();
      if (!q.length) { flushing = false; retryDelay = 0; cb(sent); return; }
      if (isOffline()) { flushing = false; cb(sent); return; }

      var item = q[0];
      /* count the attempt and persist it: `tries` is the only forensic trail
         left after a night of failures, and it survives a reload. */
      item.tries = (item.tries || 0) + 1;
      writeQueue(q);

      Api.replay(item, function (err, data) {
        if (!err) {
          sent++;
          removeById(item.id);
          /* a flushed step_complete answers with the authoritative snapshot;
             fold it into the offline cache so the next load() is already
             correct even if the UI is not on screen to reconcile it. */
          if (data && data.snapshot) { cacheSnapshot(data.snapshot); }
          retryDelay = 0;
          /* next item on a fresh turn of the event loop: a 200-deep queue
             must not become a 200-deep call stack */
          window.setTimeout(step, 0);
          return;
        }

        var status = err.status || 0;
        /* PERMANENT rejections (bad request, unknown step, gone) can never
           succeed by being retried, and a poisoned head would block every
           good event behind it forever. Drop it, name it, carry on. */
        if (status >= 400 && status < 500 &&
            status !== 401 && status !== 403 && status !== 408 && status !== 429) {
          if (window.console) {
            console.warn('[storage] dropping queued ' + item.path + ' (' + item.id +
                         '): server said ' + status +
                         ((err.data && err.data.error) ? ' ' + err.data.error : ''));
          }
          removeById(item.id);
          window.setTimeout(step, 0);
          return;
        }

        /* TRANSIENT (network down, 401 before re-login, 429, 5xx): keep the
           item, keep the order, come back later. */
        flushing = false;
        scheduleRetry();
        cb(sent);
      });
    }

    step();
  }

  /* fold a server snapshot into the offline cache without needing the app's
     live state object (flush() runs whether or not a screen is mounted). */
  function cacheSnapshot(snapshot) {
    var cached = readCache() || defaultState();
    reconcile(cached, snapshot);
  }

  /* Called by api.js after ANY successful request: a working connection is
     the best possible moment to drain the queue. */
  function noteOnline() {
    retryDelay = 0;
    flush();
  }

  /* ---- triggers: app start, reconnect, and every successful call ---- */
  if (typeof window !== 'undefined' && window.addEventListener) {
    window.addEventListener('online', function () { noteOnline(); });
    /* App start. setTimeout(0) because storage.js is the FIRST deferred
       script: Api does not exist yet at this line, but it does by the time
       the timer fires (all defers have run). */
    window.setTimeout(function () { flush(); }, 0);
  }

  /* load() returns the cached mirror if present, else defaults. The real
     truth arrives via reconcile() once the server responds on app start. */
  function load() {
    var cached = readCache();
    if (!cached) { return defaultState(); }
    var d = defaultState(), k;
    for (k in d) {
      if (d.hasOwnProperty(k) && typeof cached[k] === 'undefined') { cached[k] = d[k]; }
    }
    return cached;
  }

  /* save() updates the offline cache immediately and schedules a debounced
     low-value sync (hearts + map node) to the server. Reward-bearing changes
     do NOT go through here — they call the dedicated API endpoints, which
     return an authoritative snapshot to reconcile(). */
  function save(state) {
    writeCache(state);
    scheduleSync(state);
    return true;
  }

  /* push hearts + mapNode to the server, debounced so we aren't chatty */
  function scheduleSync(state) {
    if (typeof Api === 'undefined') { return; }
    if (syncTimer) { window.clearTimeout(syncTimer); }
    syncTimer = window.setTimeout(function () {
      Api.sync({ hearts: state.hearts, mapNode: state.mapNode }, function () {});
    }, 1200);
  }

  /* reconcile the mirror with the server's authoritative snapshot. Returns the
     updated state object (same reference if given).

     *** THE SERVER SNAPSHOT WINS. *** (brief §8, made explicit here rather
     than left implicit in the assignment order.) On login — and after every
     reward-bearing call — the fields below are OVERWRITTEN from the server,
     never merged with the local mirror, because the local mirror is a cache
     of a previous server truth plus optimistic guesses. Two devices, one
     account: the loser of a race must not resurrect stale XP by "merging".

     The one thing local state legitimately holds that the snapshot does not
     is the OFFLINE QUEUE — actions the server has not been told about yet.
     Those are not lost by this overwrite: they live in mariane_queue_v1, and
     the flush below re-posts them, after which the server sends a snapshot
     that includes them and this function overwrites again with THAT. Server
     authority is preserved and nothing earned is dropped. */
  function reconcile(state, snapshot) {
    if (!snapshot) { return state; }
    state.xp        = snapshot.xp;
    state.hearts    = snapshot.hearts;
    state.maxHearts = snapshot.maxHearts;
    state.streak    = snapshot.streak;
    state.lastDay   = snapshot.lastDay || '';
    state.mapNode   = snapshot.mapNode || 'f1';
    state.completed = snapshot.completed || {};
    state.bosses    = snapshot.bosses || {};
    writeCache(state);
    /* anything the server has not heard about yet goes now (no-op when the
       queue is empty; guarded against re-entry by the `flushing` flag). */
    if (readQueue().length) { flush(); }
    return state;
  }

  /* one-time import of a legacy local-only save (offered at first login). */
  function legacySave() {
    try {
      var raw = window.localStorage.getItem(LEGACY_KEY);
      return raw ? JSON.parse(raw) : null;
    } catch (e) { return null; }
  }
  function clearLegacy() {
    try { window.localStorage.removeItem(LEGACY_KEY); } catch (e) { /* noop */ }
  }

  /* reset only clears the LOCAL cache; server progress is authoritative and is
     reset through the account, not the browser.

     The queue goes with it, and that is a SAFETY rule, not tidiness: reset()
     is what logout calls. A queued step_complete belongs to the student who
     earned it, and replaying it into the next session on a shared classroom
     phone would credit the wrong child. Unsent work is forfeited at logout;
     the alternative is worse. */
  function reset() {
    try { window.localStorage.removeItem(KEY); } catch (e) { /* noop */ }
    clearQueue();
    return defaultState();
  }

  return {
    load: load,
    save: save,
    reset: reset,
    reconcile: reconcile,
    legacySave: legacySave,
    clearLegacy: clearLegacy,
    defaultState: defaultState,
    /* ---- offline queue (M9, brief §8) ---- */
    QUEUE_KEY: QKEY,
    eventId: eventId,
    enqueue: enqueue,
    flush: flush,
    noteOnline: noteOnline,
    queueLength: queueLength,
    queuePeek: queuePeek,
    clearQueue: clearQueue,
    isOffline: isOffline,
    setOffline: setOffline
  };
})();
